config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :tags, only: [:index, :new, :create]
  end

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"
  
  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :reviews, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'mypage'
    end
  end

  post 'guest_login', to: 'users#guest_login'
  
  get '/search', to: 'searches#search'

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def top
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<h1>Funny Land <strong>Admin</strong></h1>

<div>
  <div class="d-flex flex-row justify-content-around mt-5">
    <%= link_to "Posts", admin_posts_path %>
    <%= link_to "Users", admin_users_path %>
    <%= link_to "Tags", admin_tags_path %>
    <%= link_to "Log out", destroy_admin_session_path, method: :delete %>
  </div>
</div>