config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :tags, only: [:index, :new, :create]
  end

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"
  
  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :reviews, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'mypage'
    end
  end

  post 'guest_login', to: 'users#guest_login'
  
  get '/search', to: 'searches#search'

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  #before_action :authenticate_user!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    @tag_id = params[:tag_id]

    if @tag_id.present? && !@model.present?
      @tag = Tag.find(@tag_id)
      @records = Post.includes(:tags).where('tags.id': @tag_id)
    elsif @model == 'user'
      @records = User.search_for(@content, @method)
    else
      @records = Post.search_for(@content, @method)
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true, class: "d-flex" do |f| %>
    <%= f.text_field :content, class: "form-control me-2", placeholder: "Search", aria: { label: "Search" } %>
    <%= f.select :model, options_for_select({ "User" => "user", "Post" => "post" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit 'Search', class: "btn btn-secondary" %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @model == 'user' %>
	<h3>Users search for "<%= @content %>"</h3>
  <% @records.each do |user| %>
    <p><%= link_to user_path(user.id) do %>
      <%= image_tag user.get_profile_image(80,80) %>
    <% end %>
    <%= link_to user_path(user.id) do %>
      <%= user.name %>
    <% end %></p>
  <% end %>
<% elsif @model == 'post' %>
	<h3>Posts search for "<%= @content %>"</h3>
  <% @records.each do |post| %>
    <p><%= link_to post_path(post.id) do %>
      <%= image_tag post.get_post_image(80,80) %>
    <% end %>
    <%= link_to post_path(post.id) do %>
      <%= post.title %>
    <% end %></p>
  <% end %>
<% elsif !@model.present? && @tag_id.present? %>
	<h3>Posts search for "<%= @tag.tag_name %> tag"</h3>
  <% @records.each do |post| %>
    <p><%= link_to post_path(post.id) do %>
      <%= image_tag post.get_post_image(80,80) %>
    <% end %>
    <%= link_to post_path(post.id) do %>
      <%= post.title %>
    <% end %></p>
  <% end %>
<% end %>