config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :tags, only: [:index, :new, :create]
  end

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"
  
  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :reviews, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    collection do
      get 'mypage'
    end
  end

  post 'guest_login', to: 'users#guest_login'
  
  get '/search', to: 'searches#search'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  #belongs_to :tag

  has_many :reviews, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  has_one_attached :post_image
  has_one_attached :profile_image

  validates :title, presence: true
  validates :body, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :opening_times, presence: true
  validates :closed_day, presence: true
  #validates :latitude, presence: true
  #validates :longitude, presence: true
  validates :post_image, presence: true

  geocoded_by :address
  after_validation :geocode

  def get_post_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      post_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    post_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(title: content)
    elsif method == 'forward'
      Post.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Post.where('title LIKE ?', '%'+content)
    else
      Post.where('title LIKE ?', '%'+content+'%')
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to admin_posts_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿が完了しました。"
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def index
    @posts = Post.page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @review = Review.new
  end

  def edit
    @post = Post.find(params[:id])
    @user = current_user
    post = Post.find(params[:id])
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "更新が完了しました。"
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :address, :telephone_number, :opening_times, :closed_day, :post_image, tag_ids: [])
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to posts_path
    end
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-7 col-xl-8">
  <h3>編集</h3>

  <%= render 'layouts/error_messages', resource: @post %>

  <div>
    <%= form_with model: @post, url: post_path(@post), method: :patch do |f| %>
      <p>スポット名
      <%= f.text_field :title, class: "form-control form-control-sm" %></p>
      <p>スポット詳細
      <%= f.text_area :body, class: "form-control form-control-sm" %></p>
      <p>郵便番号
      <%= text_field_tag :zipcode, nil, class: "form-control form-control-sm" %></p>
      <p>住所
      <%= f.text_area :address, class: "form-control form-control-sm" %></p>
      <p>電話番号
      <%= f.text_field :telephone_number, class: "form-control form-control-sm" %></p>
      <p>営業時間
      <%= f.text_area :opening_times, class: "form-control form-control-sm" %></p>
      <p>定休日
      <%= f.text_area :closed_day, class: "form-control form-control-sm" %></p>
      <p>画像<br>
      <%= f.file_field :post_image, accept: "image/*" %></p>

      <div class="mb-3">
        <p>タグを選択</p>
        <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :tag_name do |b| %>
          <%= b.label { b.check_box + " #{b.text}" } %><br>
        <% end %>
      </div>

      <%= f.submit "Update", class: "btn btn-outline-success" %>
    <% end %>
      <br>
    <% if @post.user == current_user %>
      <%= link_to "Destroy", post_path(@post), method: :delete, "data-confirm" => "この投稿を本当に削除しますか？", class: "btn btn-danger" %>
    <% end %>
  </div>
  <br>
  <%= link_to "Back", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h3 class="d-flex justify-content-between align-items-center mb-5">
    <a><strong>投稿一覧</strong></a>
    <%= link_to '新規投稿はここから', new_post_path, class: 'btn btn-outline-primary', data: {turbolinks: "false"} %>
  </h3>
</div>

<table class="table">
  <thead class="text-center">
    <th style="width: 60px"></th>
    <th style="width: 100px">投稿者</th>
    <th style="width: 200px"></th>
    <th style="width: 250px">スポット名</th>
    <th style="width: 300px">スポット詳細</th>
  </thead>
  <tbody class="text-center">
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= link_to user_path(post.user.id) do %>
            <%= image_tag post.user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td>
          <%= link_to user_path(post.user.id) do %>
            <%= post.user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to post_path(post.id) do %>
            <%= image_tag post.get_post_image(100,100) %>
          <% end %>
        </td>
        <td>
          <%= link_to post_path(post.id) do %>
            <%= post.title %>
          <% end %>
        </td>
        <td><%= post.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>


    <%= paginate @posts %>

app/views/posts/new.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-7 col-xl-8">
  <h3><strong>新規投稿</strong></h3>

  <%= render 'layouts/error_messages', resource: @post %>

  <%= form_with model: @post do |f| %>
    <p>スポット名
    <%= f.text_field :title, class: "form-control form-control-sm", placeholder: "スポット名を入力してください" %></p>
    <p>スポット詳細
    <%= f.text_area :body, class: "form-control form-control-sm", placeholder: "スポット詳細を入力してください" %></p>
    <p>郵便番号
    <%= text_field_tag :zipcode, nil, class: "form-control form-control-sm", placeholder: "郵便番号を入力してください" %></p>
    <p>住所
    <%= f.text_area :address, class: "form-control form-control-sm", placeholder: "住所を入力してください" %></p>
    <p>電話番号
    <%= f.text_field :telephone_number, class: "form-control form-control-sm", placeholder: "電話番号を入力してください" %></p>
    <p>営業時間
    <%= f.text_area :opening_times, class: "form-control form-control-sm", placeholder: "営業時間を入力してください" %></p>
    <p>定休日
    <%= f.text_area :closed_day, class: "form-control form-control-sm", placeholder: "定休日を入力してください" %></p>
    <p>画像<br>
    <%= f.file_field :post_image, accept: "image/*" %></p>

    <div class="mb-3">
      <p>タグを選択</p>
      <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :tag_name do |b| %>
        <%= b.label { b.check_box + " #{b.text}" } %><br>
      <% end %>
    </div>

    <%= f.submit '投稿', class: "btn btn-outline-success" %>
  <% end %>
  <br>
  <%= link_to "Back", posts_path %>

  <%= javascript_pack_tag "jpostal",  'data-turbolinks-track': 'reload' %>
</div>

app/views/posts/show.html.erb
<h3><strong><%= @post.title %></strong></h3>

<table class="table table-striped">
  <tbody>
    <tr>
      <%= image_tag @post.get_post_image(150,150), class: "d-block mx-auto" %>
    </tr>
    <tr>
      <th width="30%", class="text-center">スポット名</th>
      <td width="70%"><%= @post.title %></td>
    </tr>
    <tr>
      <th class="text-center">詳細</th>
      <td><%= @post.body %></td>
    </tr>
    <tr>
      <th class="text-center">住所</th>
      <td><%= @post.address %></td>
    </tr>
    <tr>
      <th class="text-center">電話番号</th>
      <td><%= @post.telephone_number %></td>
    </tr>
    <tr>
      <th class="text-center">営業時間</th>
      <td><%= @post.opening_times %></td>
    </tr>
    <tr>
      <th class="text-center">定休日</th>
      <td><%= @post.closed_day %></td>
    </tr>
    <tr>
      <th class="text-center">タグ</th>
      <td>
        <% @post.tags.each do |tag| %>
          <%= link_to tag.tag_name, search_path(tag_id: tag.id), class: "badge badge-secondary" %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th class="text-center">地図</th>
      <td>
        <div id="map" data-latitude=<%= @post.latitude %> data-longitude=<%= @post.longitude %>></div>
      </td>
    </tr>
  </tbody>
</table>

<% if @post.user == current_user %>
  <div class="d-flex flex-row-reverse">
    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-success" %>
  </div>
<% end %>

<div class="container my-3">
  <h6><strong>評価・クチコミ一覧</strong></h6>
  <%= render "reviews/index", post: @post %>
</div>

<div class="container my-3">
  <h6><strong>評価・クチコミを書く</strong></h6>
  <%= render "reviews/form", post: @post, review: @review %>
</div>


<%= link_to "Back", posts_path %>

<%= javascript_pack_tag 'map', 'data-turbolinks-track': 'reload' %>